#!/usr/bin/env bash
# HYBA Fullstack one-command local launch gate.
#
# Usage:
#   bash scripts/setup_and_start.sh
#
# This script is intentionally local-first. It creates/uses a Python venv,
# upgrades pip, installs the backend requirements, installs npm dependencies,
# runs PYTHIA's autonomous bootstrap, runs the autonomous sovereign gate, starts
# the FastAPI backend, starts the frontend bridge, and proves the frontend can
# reach backend health through the bridge.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}" && pwd)"
cd "${REPO_ROOT}"

RUNTIME_DIR="${REPO_ROOT}/.hyba_runtime"
mkdir -p "${RUNTIME_DIR}"
BACKEND_LOG="${RUNTIME_DIR}/backend.log"
FRONTEND_LOG="${RUNTIME_DIR}/frontend.log"
BOOT_LOG="${RUNTIME_DIR}/launch.log"
SOVEREIGN_GATE_LOG="${RUNTIME_DIR}/autonomous_sovereign_gate.json"
PYTHIA_BOOTSTRAP_LOG="${RUNTIME_DIR}/pythia_autonomous_bootstrap.json"
: >"${BACKEND_LOG}"
: >"${FRONTEND_LOG}"
: >"${BOOT_LOG}"

BACKEND_PID=""
FRONTEND_PID=""
TAIL_PID=""

log() {
  printf '%s %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$*" | tee -a "${BOOT_LOG}"
}

show_recent_logs() {
  echo ""
  echo "--- pythia autonomous bootstrap ---"
  cat "${PYTHIA_BOOTSTRAP_LOG}" 2>/dev/null || true
  echo "--- autonomous gate output ---"
  cat "${SOVEREIGN_GATE_LOG}" 2>/dev/null || true
  echo "--- backend log tail ---"
  tail -n 80 "${BACKEND_LOG}" 2>/dev/null || true
  echo "--- frontend log tail ---"
  tail -n 80 "${FRONTEND_LOG}" 2>/dev/null || true
}

fail() {
  log "✗ $*"
  show_recent_logs
  exit 1
}

cleanup() {
  local code=$?
  if [[ -n "${TAIL_PID}" ]]; then kill "${TAIL_PID}" 2>/dev/null || true; fi
  if [[ ${code} -ne 0 ]]; then
    if [[ -n "${FRONTEND_PID}" ]]; then kill "${FRONTEND_PID}" 2>/dev/null || true; fi
    if [[ -n "${BACKEND_PID}" ]]; then kill "${BACKEND_PID}" 2>/dev/null || true; fi
  fi
}
trap cleanup EXIT
trap 'log "Stopping HYBA stack"; [[ -n "${FRONTEND_PID}" ]] && kill "${FRONTEND_PID}" 2>/dev/null || true; [[ -n "${BACKEND_PID}" ]] && kill "${BACKEND_PID}" 2>/dev/null || true; exit 0' INT TERM

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

wait_http() {
  local name="$1"
  local url="$2"
  local attempts="${3:-60}"
  for ((i = 1; i <= attempts; i++)); do
    if curl -fsS "${url}" >/dev/null 2>&1; then
      log "✓ ${name} ready: ${url}"
      return 0
    fi
    sleep 1
  done
  return 1
}

load_env_file() {
  local file="$1"
  if [[ -f "${file}" ]]; then
    log "Loading ${file}"
    set -a
    set +u
    # shellcheck disable=SC1090
    source "${file}"
    set -u
    set +a
  fi
}

ensure_local_env() {
  if [[ ! -f ".env.local" ]]; then
    log "Creating .env.local with generated local secrets"
    umask 077
    cat >.env.local <<EOF
# Generated by scripts/setup_and_start.sh
NODE_ENV=development
HYBA_ENV=development
JWT_SECRET=$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
)
HYBA_INTERNAL_HEALTH_TOKEN=$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
)
PULVINI_BACKEND_URL=http://127.0.0.1:3001
HYBA_SPAWN_BACKEND=false
HYBA_ALLOW_DEV_FIXTURES=false
HYBA_ENABLE_LIVE_STRATUM=true
HYBA_ENABLE_MINING_AUTOCONNECT=false
HYBA_ENABLE_AUDIT_LOGGING=true
HYBA_ENABLE_AUTONOMOUS_MINING=true
HYBA_AUTONOMY_LEVEL=autonomous
HYBA_REFLEXIVE_LOOP_ENABLED=true
HYBA_COMPRESSION_DRIVE_ENABLED=true
HYBA_BOOTSTRAP_REFLEXIVE_EPOCHS=2
HYBA_AUTONOMOUS_MAX_HASHRATE_EHS=1.0
HYBA_AUTONOMOUS_MAX_POWER_WATTS=500
HYBA_AUTONOMOUS_MIN_PHI_COHERENCE=0.70
BACKEND_PROXY_TIMEOUT_MS=30000
EOF
  fi

  load_env_file ".env.local"
  load_env_file ".env.mining.local"

  export NODE_ENV="${NODE_ENV:-development}"
  export HYBA_ENV="${HYBA_ENV:-${NODE_ENV}}"
  export BACKEND_PORT="${BACKEND_PORT:-3001}"
  export PORT="${PORT:-3000}"
  export HOST="${HOST:-127.0.0.1}"
  export PULVINI_BACKEND_URL="${PULVINI_BACKEND_URL:-http://127.0.0.1:${BACKEND_PORT}}"
  export HYBA_SPAWN_BACKEND="${HYBA_SPAWN_BACKEND:-false}"
  export HYBA_ALLOW_DEV_FIXTURES="${HYBA_ALLOW_DEV_FIXTURES:-false}"
  export HYBA_ENABLE_LIVE_STRATUM="${HYBA_ENABLE_LIVE_STRATUM:-true}"
  export HYBA_ENABLE_MINING_AUTOCONNECT="${HYBA_ENABLE_MINING_AUTOCONNECT:-false}"
  export HYBA_ENABLE_AUDIT_LOGGING="${HYBA_ENABLE_AUDIT_LOGGING:-true}"
  export HYBA_ENABLE_AUTONOMOUS_MINING="${HYBA_ENABLE_AUTONOMOUS_MINING:-true}"
  export HYBA_AUTONOMY_LEVEL="${HYBA_AUTONOMY_LEVEL:-autonomous}"
  export HYBA_REFLEXIVE_LOOP_ENABLED="${HYBA_REFLEXIVE_LOOP_ENABLED:-true}"
  export HYBA_COMPRESSION_DRIVE_ENABLED="${HYBA_COMPRESSION_DRIVE_ENABLED:-true}"
  export HYBA_BOOTSTRAP_REFLEXIVE_EPOCHS="${HYBA_BOOTSTRAP_REFLEXIVE_EPOCHS:-2}"
  export HYBA_AUTONOMOUS_MAX_HASHRATE_EHS="${HYBA_AUTONOMOUS_MAX_HASHRATE_EHS:-1.0}"
  export HYBA_AUTONOMOUS_MAX_POWER_WATTS="${HYBA_AUTONOMOUS_MAX_POWER_WATTS:-500}"
  export HYBA_AUTONOMOUS_MIN_PHI_COHERENCE="${HYBA_AUTONOMOUS_MIN_PHI_COHERENCE:-0.70}"
  export PYTHONPATH="${REPO_ROOT}/python_backend${PYTHONPATH:+:${PYTHONPATH}}"
}

run_pythia_bootstrap() {
  if [[ "${HYBA_ENABLE_AUTONOMOUS_MINING}" != "true" ]]; then
    log "PYTHIA autonomous bootstrap skipped by HYBA_ENABLE_AUTONOMOUS_MINING=${HYBA_ENABLE_AUTONOMOUS_MINING}"
    return 0
  fi
  log "Bootstrapping PYTHIA self-healing/self-optimising autonomy"
  if ! python scripts/pythia_autonomous_bootstrap.py \
    --epochs "${HYBA_BOOTSTRAP_REFLEXIVE_EPOCHS}" \
    --capacity-ehs "${HYBA_AUTONOMOUS_MAX_HASHRATE_EHS}" \
    --output "${PYTHIA_BOOTSTRAP_LOG}" \
    >"${RUNTIME_DIR}/pythia_autonomous_bootstrap.stdout.json"; then
    fail "PYTHIA autonomous bootstrap failed"
  fi
  log "✓ PYTHIA autonomous bootstrap complete"
}

run_sovereign_gate() {
  local mode="command-room"
  if [[ "${NODE_ENV}" == "production" || "${HYBA_ENV}" == "production" ]]; then
    mode="live"
  fi
  log "Running autonomous sovereign gate in ${mode} mode"
  if ! python scripts/mining_autonomous_sovereign_gate.py --mode "${mode}" --write >"${SOVEREIGN_GATE_LOG}"; then
    fail "Autonomous sovereign gate returned NO-GO"
  fi
  log "✓ Autonomous sovereign gate returned GO"
}

main() {
  log "╔════════════════════════════════════════════════════════════════╗"
  log "║        HYBA FULLSTACK LOCAL LAUNCH GATE                       ║"
  log "╚════════════════════════════════════════════════════════════════╝"

  require_command python3
  require_command node
  require_command npm
  require_command curl

  if [[ ! -f "requirements.txt" || ! -f "package.json" || ! -d "python_backend" ]]; then
    fail "Run from HYBA_FULLSTACK root; required files/directories are missing"
  fi

  python3 - <<'PY' || fail "Python 3.12+ is required"
import sys
raise SystemExit(0 if sys.version_info >= (3, 12) else 1)
PY
  log "✓ Python version: $(python3 --version)"
  log "✓ Node version: $(node --version)"
  log "✓ npm version: $(npm --version)"

  ensure_local_env

  log "Setting up Python virtual environment"
  if [[ ! -d "venv" ]]; then
    python3 -m venv venv
  fi
  # shellcheck disable=SC1091
  source venv/bin/activate
  python -m pip install --upgrade pip setuptools wheel
  if [[ "${HYBA_SKIP_PYTHON_INSTALL:-false}" != "true" ]]; then
    python -m pip install -r requirements.txt
  else
    log "Skipping Python dependency install"
  fi

  log "Checking backend import"
  python - <<'PY'
import sys
sys.path.insert(0, 'python_backend')
import hyba_genesis_api.main  # noqa: F401
print('backend import ok')
PY

  run_pythia_bootstrap

  if [[ "${HYBA_SKIP_NPM_INSTALL:-false}" != "true" ]]; then
    if [[ -f "package-lock.json" ]]; then
      log "Installing npm dependencies with npm ci"
      npm ci --include=dev
    else
      log "Installing npm dependencies with npm install"
      npm install --include=dev
    fi
  else
    log "Skipping npm dependency install"
  fi

  if [[ "${NODE_ENV}" == "production" || "${HYBA_RUN_FRONTEND_BUILD:-false}" == "true" ]]; then
    log "Running frontend/server build"
    npm run build
  fi

  run_sovereign_gate

  log "Starting FastAPI backend on http://127.0.0.1:${BACKEND_PORT}"
  python -m uvicorn hyba_genesis_api.main:app \
    --app-dir python_backend \
    --host 127.0.0.1 \
    --port "${BACKEND_PORT}" \
    >>"${BACKEND_LOG}" 2>&1 &
  BACKEND_PID=$!

  wait_http "Backend readiness" "http://127.0.0.1:${BACKEND_PORT}/api/health/readiness" 90 \
    || wait_http "Backend health" "http://127.0.0.1:${BACKEND_PORT}/health" 20 \
    || fail "Backend did not become healthy"

  log "Starting frontend/bridge on http://127.0.0.1:${PORT}"
  PORT="${PORT}" \
  HOST="127.0.0.1" \
  PULVINI_BACKEND_URL="http://127.0.0.1:${BACKEND_PORT}" \
  HYBA_SPAWN_BACKEND=false \
  npx tsx src/server.ts \
    >>"${FRONTEND_LOG}" 2>&1 &
  FRONTEND_PID=$!

  wait_http "Frontend bridge" "http://127.0.0.1:${PORT}/bridge/health" 90 \
    || fail "Frontend/bridge did not become healthy"

  wait_http "Frontend-to-backend proxy" "http://127.0.0.1:${PORT}/health" 30 \
    || fail "Frontend bridge cannot reach backend health"

  log "╔════════════════════════════════════════════════════════════════╗"
  log "║                    HYBA STACK IS RUNNING                       ║"
  log "╠════════════════════════════════════════════════════════════════╣"
  log "║ Frontend:        http://127.0.0.1:${PORT}"
  log "║ Backend API:     http://127.0.0.1:${BACKEND_PORT}"
  log "║ Backend PID:     ${BACKEND_PID}"
  log "║ Frontend PID:    ${FRONTEND_PID}"
  log "║ Logs:            ${RUNTIME_DIR}"
  log "║ PYTHIA evidence: ${PYTHIA_BOOTSTRAP_LOG}"
  log "║ Gate evidence:   ${SOVEREIGN_GATE_LOG}"
  log "╚════════════════════════════════════════════════════════════════╝"


}

main "$@"
