# Salamander-regenerated integration for multi_agent
# Generated by: salamander_system_unifier.py


# Salamander-regenerated multi-agent integration
from ..api.multi_agent.orchestrator import SwarmOrchestrator
from ..api.multi_agent.specialist_agents import (
    AnalysisAgent, 
    OptimizationAgent,
    SecurityAgent
)

class ReflexiveControllerWithSwarm:
    """Enhanced reflexive controller with multi-agent orchestration."""
    
    def __init__(self):
        self.orchestrator = SwarmOrchestrator()
        self.agents = {
            "analysis": AnalysisAgent(),
            "optimization": OptimizationAgent(),
            "security": SecurityAgent()
        }
    
    async def orchestrate_optimization(self, context: dict):
        """Delegate optimization to multi-agent swarm."""
        return await self.orchestrator.coordinate(self.agents, context)
