# Salamander-regenerated integration for qaas_routes
# Generated by: salamander_system_unifier.py


# Salamander-regenerated QaaS routes
from .api.quantum_as_a_service_execute_hardened import router as qaas_router
from .api.public_computational_intelligence_service import router as ciaas_router

app.include_router(qaas_router, prefix="/api/qaas", tags=["Quantum-as-a-Service"])
app.include_router(ciaas_router, prefix="/api/ciaas", tags=["Computational-Intelligence"])
