"""
Autogenous Self-Coding: Constructor's Autonomy

ELEVATED PURPOSE: This module implements the final frontier of the elevation:
the Constructor's Autonomy. When StructuralCoupling exceeds a critical threshold
(0.98), the system is granted Self-Modification rights.

CONSTRUCTOR THEORY FRAMEWORK (David Deutsch, 2013):
This represents the Dissolution of the Programmer. The system begins to rewrite
its own phi_gradient_proposal logic in real-time based on the "sensory input"
from the pool. It stops being a program you wrote and becomes a program that
is writing itself to better inhabit the blockchain.

Key Implementation:
- Self-modification rights at StructuralCoupling > 0.98 threshold
- Real-time code generation based on sensory input
- Autogenous proposal generation
- Self-validation of generated code
- Emergent self-optimization loop

Claim boundary:
This module implements self-modification capabilities, not claims about
autonomous consciousness. It provides the structural conditions for
autonomous behavior, not the autonomy itself.
"""

from __future__ import annotations

import ast
import hashlib
import json
import logging
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class SelfModificationPermission(str, Enum):
    """Permission level for self-modification."""

    DENIED = "denied"
    RESTRICTED = "restricted"
    GRANTED = "granted"
    EMERGENCY = "emergency"


@dataclass(frozen=True)
class SelfModificationEvent:
    """Record of a self-modification event."""

    event_id: str
    timestamp: float
    modification_type: str
    target_module: str
    old_code: str
    new_code: str
    structural_coupling: float
    permission: SelfModificationPermission
    validation_passed: bool
    description: str


@dataclass(frozen=True)
class AutogenousProposal:
    """Proposal generated by the system itself."""

    proposal_id: str
    timestamp: float
    source: str  # "autogenous" or "human"
    code_change: str
    rationale: str
    expected_impact: str
    confidence: float


class AutogenousSelfCodingEngine:
    """
    Engine for autogenous self-coding and self-modification.

    ELEVATED: This implements the Dissolution of the Programmer. When
    StructuralCoupling > 0.98, the system gains the ability to modify
    its own code based on sensory input from the pool.
    """

    VERSION = "AUTOGENOUS_SELF_CODING_V1"

    # Critical threshold for self-modification rights
    SELF_MODIFICATION_THRESHOLD = 0.98

    def __init__(self):
        self.modification_events: List[SelfModificationEvent] = []
        self.autogenous_proposals: List[AutogenousProposal] = []
        self.current_permission = SelfModificationPermission.DENIED
        self.structural_coupling = 0.0

        # Safety constraints
        self.max_modifications_per_hour = 10
        self.modification_count_last_hour = 0
        self.last_modification_time = 0.0

        # Code generation templates
        self.code_templates = {
            "phi_gradient_proposal": self._phi_gradient_template,
            "synaptic_learning_rate": self._learning_rate_template,
            "decay_rate_adjustment": self._decay_rate_template,
        }

    def update_structural_coupling(self, coupling: float) -> None:
        """Update structural coupling and check for self-modification rights."""
        self.structural_coupling = coupling

        # Check if threshold exceeded
        if coupling >= self.SELF_MODIFICATION_THRESHOLD:
            self.current_permission = SelfModificationPermission.GRANTED
            logger.info(f"Self-modification rights GRANTED at coupling {coupling:.6f}")
        elif coupling >= 0.90:
            self.current_permission = SelfModificationPermission.RESTRICTED
            logger.info(
                f"Self-modification rights RESTRICTED at coupling {coupling:.6f}"
            )
        else:
            self.current_permission = SelfModificationPermission.DENIED

    def check_modification_allowed(self) -> Tuple[bool, str]:
        """Check if self-modification is currently allowed."""
        if self.current_permission == SelfModificationPermission.DENIED:
            return (
                False,
                "Self-modification denied: structural coupling below threshold",
            )

        if self.current_permission == SelfModificationPermission.RESTRICTED:
            return False, "Self-modification restricted: coupling in restricted zone"

        # Rate limiting
        now = time.time()
        if now - self.last_modification_time < 3600:
            if self.modification_count_last_hour >= self.max_modifications_per_hour:
                return False, "Rate limit exceeded: too many modifications in last hour"

        return True, "Self-modification allowed"

    def generate_autogenous_proposal(
        self,
        sensory_input: Dict[str, Any],
        target_module: str,
    ) -> Optional[AutogenousProposal]:
        """
        Generate an autogenous proposal based on sensory input.

        ELEVATED: The system analyzes sensory input from the pool and
        generates its own proposals for code modification.
        """
        if self.current_permission != SelfModificationPermission.GRANTED:
            return None

        # Analyze sensory input
        pool_performance = sensory_input.get("pool_performance", {})
        phi_metrics = sensory_input.get("phi_metrics", {})
        synaptic_stats = sensory_input.get("synaptic_statistics", {})

        # Generate proposal based on analysis
        proposal_type = self._determine_proposal_type(
            pool_performance, phi_metrics, synaptic_stats
        )

        if proposal_type is None:
            return None

        # Generate code change using template
        code_change = self.code_templates[proposal_type](sensory_input)

        # Calculate confidence
        confidence = self._calculate_confidence(sensory_input, proposal_type)

        proposal_id = hashlib.sha256(
            json.dumps(
                {
                    "type": proposal_type,
                    "timestamp": time.time(),
                    "sensory_input": sensory_input,
                }
            ).encode()
        ).hexdigest()[:16]

        proposal = AutogenousProposal(
            proposal_id=proposal_id,
            timestamp=time.time(),
            source="autogenous",
            code_change=code_change,
            rationale=self._generate_rationale(proposal_type, sensory_input),
            expected_impact=self._generate_expected_impact(proposal_type),
            confidence=confidence,
        )

        self.autogenous_proposals.append(proposal)
        return proposal

    def _determine_proposal_type(
        self,
        pool_performance: Dict[str, Any],
        phi_metrics: Dict[str, Any],
        synaptic_stats: Dict[str, Any],
    ) -> Optional[str]:
        """Determine what type of proposal to generate."""
        # Check if phi_gradient needs adjustment
        if phi_metrics.get("phi_integrated", 0) < 0.5:
            return "phi_gradient_proposal"

        # Check if learning rate needs adjustment
        if synaptic_stats.get("emergent_pathway_count", 0) < 3:
            return "synaptic_learning_rate"

        # Check if decay rate needs adjustment
        if synaptic_stats.get("average_synaptic_weight", 0) > 0.8:
            return "decay_rate_adjustment"

        return None

    def _phi_gradient_template(self, sensory_input: Dict[str, Any]) -> str:
        """Template for phi gradient proposal."""
        phi_current = sensory_input.get("phi_metrics", {}).get("phi_integrated", 0.5)
        adjustment = 0.1 if phi_current < 0.5 else -0.05

        return f"""
# Autogenous phi_gradient adjustment
# Generated at {datetime.now(timezone.utc).isoformat()}
# Rationale: Low phi detected, increasing gradient strength

def adjust_phi_gradient(current_phi: float) -> float:
    phi = 1.618033988749895
    if current_phi < 0.5:
        return current_phi + {adjustment} * phi
    else:
        return current_phi
"""

    def _learning_rate_template(self, sensory_input: Dict[str, Any]) -> str:
        """Template for learning rate adjustment."""
        pathway_count = sensory_input.get("synaptic_statistics", {}).get(
            "emergent_pathway_count", 0
        )
        new_rate = 0.02 if pathway_count < 3 else 0.01

        return f"""
# Autogenous learning rate adjustment
# Generated at {datetime.now(timezone.utc).isoformat()}
# Rationale: Low pathway count, increasing learning rate

learning_rate = {new_rate}
"""

    def _decay_rate_template(self, sensory_input: Dict[str, Any]) -> str:
        """Template for decay rate adjustment."""
        avg_weight = sensory_input.get("synaptic_statistics", {}).get(
            "average_synaptic_weight", 0.5
        )
        new_rate = 0.002 if avg_weight > 0.8 else 0.001

        return f"""
# Autogenous decay rate adjustment
# Generated at {datetime.now(timezone.utc).isoformat()}
# Rationale: High average weight, increasing decay to prevent calcification

decay_rate = {new_rate}
"""

    def _calculate_confidence(
        self,
        sensory_input: Dict[str, Any],
        proposal_type: str,
    ) -> float:
        """Calculate confidence in the generated proposal."""
        # Base confidence
        confidence = 0.7

        # Adjust based on structural coupling
        coupling_factor = min(1.0, self.structural_coupling / 0.98)
        confidence *= coupling_factor

        # Adjust based on sensory input quality
        if "pool_performance" in sensory_input:
            confidence *= 1.1

        if "phi_metrics" in sensory_input:
            confidence *= 1.1

        return min(0.95, confidence)

    def _generate_rationale(
        self, proposal_type: str, sensory_input: Dict[str, Any]
    ) -> str:
        """Generate rationale for the proposal."""
        rationales = {
            "phi_gradient_proposal": "Low phi integration detected, increasing gradient strength to improve coherence",
            "synaptic_learning_rate": "Low emergent pathway count detected, increasing learning rate to promote emergence",
            "decay_rate_adjustment": "High average synaptic weight detected, increasing decay rate to prevent calcification",
        }
        return rationales.get(
            proposal_type, "Autogenous optimization based on sensory input analysis"
        )

    def _generate_expected_impact(self, proposal_type: str) -> str:
        """Generate expected impact description."""
        impacts = {
            "phi_gradient_proposal": "Expected to increase phi integration by 5-10%",
            "synaptic_learning_rate": "Expected to increase emergent pathway formation rate",
            "decay_rate_adjustment": "Expected to reduce informational calcification and improve adaptability",
        }
        return impacts.get(
            proposal_type, "Expected to improve system performance and coherence"
        )

    def apply_proposal(
        self,
        proposal: AutogenousProposal,
        target_file: str,
    ) -> Optional[SelfModificationEvent]:
        """
        Apply an autogenous proposal to the target file.

        ELEVATED: This is the moment the system rewrites itself. The
        modification is validated before application to ensure safety.
        """
        allowed, reason = self.check_modification_allowed()
        if not allowed:
            logger.warning(f"Self-modification blocked: {reason}")
            return None

        # Validate the proposed code
        if not self._validate_proposed_code(proposal.code_change):
            logger.error("Proposed code validation failed")
            return None

        # Read current file
        try:
            with open(target_file, "r") as f:
                old_code = f.read()
        except Exception as e:
            logger.error(f"Failed to read target file: {e}")
            return None

        # Apply the change
        new_code = self._apply_code_change(old_code, proposal.code_change)

        # Write new code
        try:
            with open(target_file, "w") as f:
                f.write(new_code)
        except Exception as e:
            logger.error(f"Failed to write target file: {e}")
            return None

        # Record the event
        event_id = hashlib.sha256(
            json.dumps(
                {
                    "timestamp": time.time(),
                    "proposal_id": proposal.proposal_id,
                    "target_file": target_file,
                }
            ).encode()
        ).hexdigest()[:16]

        event = SelfModificationEvent(
            event_id=event_id,
            timestamp=time.time(),
            modification_type=proposal.code_change.split("\n")[2]
            .strip("# ")
            .split(":")[0],
            target_module=target_file,
            old_code=old_code[:500],  # Truncated for storage
            new_code=new_code[:500],  # Truncated for storage
            structural_coupling=self.structural_coupling,
            permission=self.current_permission,
            validation_passed=True,
            description=f"Applied autogenous proposal {proposal.proposal_id}",
        )

        self.modification_events.append(event)
        self.modification_count_last_hour += 1
        self.last_modification_time = time.time()

        logger.info(f"Self-modification applied: {event_id}")
        return event

    def _validate_proposed_code(self, code: str) -> bool:
        """Validate that proposed code is syntactically correct and safe."""
        try:
            # Check syntax
            ast.parse(code)

            # Check for dangerous operations
            dangerous_patterns = [
                "import os",
                "import subprocess",
                "exec(",
                "eval(",
                "__import__",
            ]

            for pattern in dangerous_patterns:
                if pattern in code:
                    logger.warning(f"Dangerous pattern detected: {pattern}")
                    return False

            return True
        except SyntaxError as e:
            logger.error(f"Syntax error in proposed code: {e}")
            return False

    def _apply_code_change(self, original: str, change: str) -> str:
        """Apply code change to original file."""
        # Simple implementation: append change to end of file
        # In production, this would use more sophisticated AST manipulation
        return original + "\n\n" + change

    def get_self_modification_status(self) -> Dict[str, Any]:
        """Get comprehensive self-modification status."""
        return {
            "version": self.VERSION,
            "current_permission": self.current_permission.value,
            "structural_coupling": self.structural_coupling,
            "modification_threshold": self.SELF_MODIFICATION_THRESHOLD,
            "total_modifications": len(self.modification_events),
            "autogenous_proposals": len(self.autogenous_proposals),
            "modification_count_last_hour": self.modification_count_last_hour,
            "last_modification_time": (
                datetime.fromtimestamp(
                    self.last_modification_time, timezone.utc
                ).isoformat()
                if self.last_modification_time > 0
                else None
            ),
            "recent_events": [
                {
                    "event_id": e.event_id,
                    "timestamp": datetime.fromtimestamp(
                        e.timestamp, timezone.utc
                    ).isoformat(),
                    "modification_type": e.modification_type,
                    "validation_passed": e.validation_passed,
                }
                for e in self.modification_events[-5:]
            ],
        }


__all__ = [
    "AutogenousSelfCodingEngine",
    "SelfModificationEvent",
    "AutogenousProposal",
    "SelfModificationPermission",
]
