"""Church-Turing-Deutsch formalism helpers for substrate-agnostic math.

This module implements a deliberately bounded interpretation of the CTD
position paper used by HYBA/PYTHIA: Hilbert-space mathematics can be executed on
ordinary software substrates, while claims about physical quantum hardware or
asymptotic quantum speedup remain explicit non-claims unless separately proven.

The implementation focuses on auditable invariants:
  * normalized complex state vectors in finite Hilbert spaces,
  * density matrices and Born-rule probabilities,
  * unitary evolution with norm preservation,
  * PULVINI/φ working-set compression with retained reconstruction kernels, and
  * a claim-boundary review packet separating implemented mathematics from
    unproven physical/computational claims.
"""

from __future__ import annotations

import math
import time
from dataclasses import asdict, dataclass
from typing import Any, Iterable, Mapping, Sequence

try:  # Optional at import time so complexity-only benchmark reports can run.
    import numpy as np
except ModuleNotFoundError:  # pragma: no cover - exercised in minimal environments
    np = None  # type: ignore[assignment]

from .phi_config import PHI


def _require_numpy() -> Any:
    if np is None:
        raise ModuleNotFoundError("numpy is required for Hilbert-space numeric operations")
    return np


@dataclass(frozen=True, init=False)
class HilbertState:
    """A normalized finite-dimensional complex Hilbert-space state."""

    amplitudes: np.ndarray

    def __init__(
        self, amplitudes: Sequence[complex] | None = None, *, vector: Sequence[complex] | None = None
    ) -> None:
        source = amplitudes if amplitudes is not None else vector
        if source is None:
            raise ValueError("Hilbert state requires amplitudes or vector")
        normalized = self._normalize(source)
        object.__setattr__(self, "amplitudes", normalized)

    @staticmethod
    def _normalize(amplitudes: Sequence[complex]) -> Any:
        numpy = _require_numpy()
        values = numpy.asarray(amplitudes, dtype=numpy.complex128).reshape(-1)
        if values.size == 0:
            raise ValueError("Hilbert state must contain at least one amplitude")
        norm = float(numpy.linalg.norm(values))
        if not math.isfinite(norm) or norm <= 0.0:
            raise ValueError("Hilbert state norm must be finite and positive")
        return values / norm

    @classmethod
    def from_amplitudes(cls, amplitudes: Sequence[complex]) -> "HilbertState":
        return cls(amplitudes)

    @property
    def dimension(self) -> int:
        return int(self.amplitudes.size)

    def density_matrix(self) -> np.ndarray:
        psi = self.amplitudes.reshape(-1, 1)
        return psi @ psi.conj().T

    def trace(self) -> float:
        numpy = _require_numpy()
        return float(numpy.trace(self.density_matrix()).real)

    def eigenvalues(self) -> Any:
        numpy = _require_numpy()
        return numpy.linalg.eigvalsh(self.density_matrix()).real

    def born_probabilities(self) -> np.ndarray:
        numpy = _require_numpy()
        probabilities = numpy.abs(self.amplitudes) ** 2
        return probabilities / max(float(numpy.sum(probabilities)), numpy.finfo(float).tiny)

    def evolve(self, unitary: np.ndarray, *, atol: float = 1e-9) -> "HilbertState":
        numpy = _require_numpy()
        matrix = numpy.asarray(unitary, dtype=numpy.complex128)
        if matrix.shape != (self.dimension, self.dimension):
            raise ValueError(
                f"unitary shape {matrix.shape!r} does not match state dimension {self.dimension}"
            )
        identity = numpy.eye(self.dimension, dtype=numpy.complex128)
        if not numpy.allclose(matrix.conj().T @ matrix, identity, atol=atol):
            raise ValueError("evolution operator must be unitary")
        return HilbertState.from_amplitudes(matrix @ self.amplitudes)


def compute_phi_resonance(nonce: int, harmonics: Sequence[int] = (1, 2, 3, 5, 8, 13, 21)) -> float:
    """Compute bounded multi-harmonic Φ-resonance for a nonce-like integer.

    The score is a formalism feature, not evidence that Bitcoin nonces are
    causally generated by Φ. Multiple Fibonacci harmonics are used to avoid
    overfitting to one phase window while retaining a deterministic [0, 1] score.
    """

    value = int(nonce) & 0xFFFFFFFF
    best = 0.0
    for harmonic in harmonics:
        phase = (value * (PHI ** int(harmonic))) % 1.0
        best = max(best, 1.0 - 2.0 * abs(phase - 0.5))
    return float(max(0.0, min(1.0, best)))


@dataclass(frozen=True)
class BuresManifold:
    """Minimal finite-dimensional Bures manifold stability model."""

    dimension: int

    def __post_init__(self) -> None:
        if int(self.dimension) < 2:
            raise ValueError("dimension must be >= 2")

    def compute_ricci_scalar(self) -> float:
        dim = int(self.dimension)
        return float((dim - 1) / dim)


@dataclass(frozen=True)
class CTDClaimReview:
    """Explicit review boundary for what this software implementation proves."""

    implements_hilbert_space_math: bool
    implements_born_rule: bool
    implements_unitary_evolution: bool
    uses_pulvini_phi_compression: bool
    substrate_agnostic_math: bool
    claims_physical_quantum_hardware: bool
    claims_universal_quantum_speedup: bool
    claims_rsa_break: bool
    claims_physical_quantum_computers_unnecessary: bool

    @property
    def rigorous(self) -> bool:
        return (
            self.implements_hilbert_space_math
            and self.implements_born_rule
            and self.implements_unitary_evolution
            and self.uses_pulvini_phi_compression
            and self.substrate_agnostic_math
            and not self.claims_physical_quantum_hardware
            and not self.claims_universal_quantum_speedup
            and not self.claims_rsa_break
            and not self.claims_physical_quantum_computers_unnecessary
        )

    def as_dict(self) -> dict[str, bool]:
        data = asdict(self)
        data["rigorous"] = self.rigorous
        return data


@dataclass(frozen=True)
class DeutschPulviniBenchmarkRow:
    """Complexity row comparing dense states with structured PULVINI/MPS states."""

    qubits: int
    dense_complex_amplitudes: int
    dense_state_bytes: int
    phi_bond_dimension: int
    structured_parameters: int
    structured_state_bytes: int
    pulvini_working_set_ratio: float
    unstructured_parameter_ratio: float
    structured_state_class: str

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class DeutschPulviniBenchmarkReport:
    """Honest Deutsch/PULVINI benchmark report.

    The report is intentionally not a speedup claim. It records the empirical
    interpretation requested by review: PULVINI/φ helps structured states, but
    does not remove the exponential wall for arbitrary high-entanglement states.
    """

    rows: tuple[DeutschPulviniBenchmarkRow, ...]
    conclusion: str
    validates_exponential_wall: bool
    claims_exponential_breakthrough: bool
    claims_quantum_hardware_obsolete: bool

    @property
    def rigorous(self) -> bool:
        return (
            self.validates_exponential_wall
            and not self.claims_exponential_breakthrough
            and not self.claims_quantum_hardware_obsolete
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "rows": [row.as_dict() for row in self.rows],
            "conclusion": self.conclusion,
            "validates_exponential_wall": self.validates_exponential_wall,
            "claims_exponential_breakthrough": self.claims_exponential_breakthrough,
            "claims_quantum_hardware_obsolete": self.claims_quantum_hardware_obsolete,
            "rigorous": self.rigorous,
        }


@dataclass(frozen=True)
class CTDExperimentPacket:
    """Replayable evidence packet for one formalism experiment."""

    dimension: int
    norm_before: float
    norm_after: float
    born_sum: float
    density_trace: float
    density_hermiticity_error: float
    compression_ratio: float
    reconstruction_error: float
    reversible_compression: bool
    phi: float
    elapsed_seconds: float
    claim_review: CTDClaimReview

    def as_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["claim_review"] = self.claim_review.as_dict()
        return data


def golden_phase_state(dimension: int, *, phase_seed: float = 0.0) -> HilbertState:
    """Build a deterministic φ-phase Hilbert state for repeatable experiments."""

    if int(dimension) <= 0:
        raise ValueError("dimension must be positive")
    numpy = _require_numpy()
    indices = numpy.arange(int(dimension), dtype=numpy.float64)
    golden_angle = 2.0 * numpy.pi / (PHI * PHI)
    phases = phase_seed + indices * golden_angle
    envelope = 1.0 / numpy.sqrt(indices + 1.0)
    return HilbertState.from_amplitudes(envelope * numpy.exp(1j * phases))


def golden_ratio_unitary(dimension: int) -> np.ndarray:
    """Return a deterministic diagonal unitary with φ-spaced phases."""

    if int(dimension) <= 0:
        raise ValueError("dimension must be positive")
    numpy = _require_numpy()
    indices = numpy.arange(int(dimension), dtype=numpy.float64)
    phases = (indices + 1.0) * (2.0 * numpy.pi / (PHI * PHI))
    return numpy.diag(numpy.exp(1j * phases)).astype(numpy.complex128)


def phi_log_bond_dimension(qubits: int, *, minimum: int = 2) -> int:
    """Return a φ-logarithmic bond dimension for structured-state estimates."""

    if int(qubits) <= 0:
        raise ValueError("qubits must be positive")
    return max(int(minimum), int(math.ceil(math.log(int(qubits) + 1, PHI))))


def dense_state_bytes(qubits: int, *, bytes_per_complex: int = 16) -> int:
    """Exact dense state-vector memory for an arbitrary n-qubit pure state."""

    if int(qubits) <= 0:
        raise ValueError("qubits must be positive")
    return (1 << int(qubits)) * int(bytes_per_complex)


def structured_mps_bytes(
    qubits: int,
    *,
    bond_dimension: int | None = None,
    physical_dimension: int = 2,
    bytes_per_complex: int = 16,
) -> int:
    """Polynomial memory estimate for a low-entanglement MPS-like state."""

    if int(qubits) <= 0:
        raise ValueError("qubits must be positive")
    chi = phi_log_bond_dimension(qubits) if bond_dimension is None else int(bond_dimension)
    if chi <= 0:
        raise ValueError("bond_dimension must be positive")
    return int(qubits) * int(physical_dimension) * chi * chi * int(bytes_per_complex)


def run_deutsch_pulvini_benchmark(
    qubits: Iterable[int] = (30, 50, 100, 200, 1000),
    *,
    pulvini_working_set_ratio: float = 1.04,
) -> DeutschPulviniBenchmarkReport:
    """Benchmark the honest pivot: structure helps; arbitrary states remain exponential.

    Dense-state memory is computed exactly as ``2**n`` complex amplitudes. The
    structured side uses a φ-logarithmic MPS bond dimension, which is only valid
    for low-entanglement / structured workloads. The ratio therefore acts as a
    claim boundary, not as evidence that arbitrary quantum states are compressed.
    """

    if float(pulvini_working_set_ratio) <= 0.0:
        raise ValueError("pulvini_working_set_ratio must be positive")

    rows: list[DeutschPulviniBenchmarkRow] = []
    for qubit_count in qubits:
        n = int(qubit_count)
        if n <= 0:
            raise ValueError("all qubit counts must be positive")
        dense_amplitudes = 1 << n
        dense_bytes = dense_amplitudes * 16
        chi = phi_log_bond_dimension(n)
        structured_bytes = structured_mps_bytes(n, bond_dimension=chi)
        structured_parameters = structured_bytes // 16
        compressed_structured_bytes = max(
            1, int(math.ceil(structured_bytes / pulvini_working_set_ratio))
        )
        rows.append(
            DeutschPulviniBenchmarkRow(
                qubits=n,
                dense_complex_amplitudes=dense_amplitudes,
                dense_state_bytes=dense_bytes,
                phi_bond_dimension=chi,
                structured_parameters=structured_parameters,
                structured_state_bytes=compressed_structured_bytes,
                pulvini_working_set_ratio=float(pulvini_working_set_ratio),
                unstructured_parameter_ratio=float(
                    dense_amplitudes / max(1, structured_parameters)
                ),
                structured_state_class="low_entanglement_phi_log_mps",
            )
        )

    return DeutschPulviniBenchmarkReport(
        rows=tuple(rows),
        conclusion=(
            "PULVINI/φ provides polynomial working-set structure for low-entanglement "
            "states, while arbitrary unstructured states still require exponentially "
            "many dense amplitudes; this validates the CTD/Deutsch complexity boundary."
        ),
        validates_exponential_wall=True,
        claims_exponential_breakthrough=False,
        claims_quantum_hardware_obsolete=False,
    )


def review_ctd_claims(overrides: Mapping[str, bool] | None = None) -> CTDClaimReview:
    """Return the default rigorous claim boundary, with optional explicit overrides."""

    values: dict[str, bool] = {
        "implements_hilbert_space_math": True,
        "implements_born_rule": True,
        "implements_unitary_evolution": True,
        "uses_pulvini_phi_compression": True,
        "substrate_agnostic_math": True,
        "claims_physical_quantum_hardware": False,
        "claims_universal_quantum_speedup": False,
        "claims_rsa_break": False,
        "claims_physical_quantum_computers_unnecessary": False,
    }
    if overrides:
        values.update({key: bool(value) for key, value in overrides.items() if key in values})
    return CTDClaimReview(**values)


def run_ctd_formalism_experiment(
    dimension: int = 32,
    *,
    fold_depth: int = 2,
    phase_seed: float = 0.0,
) -> CTDExperimentPacket:
    """Run a bounded CTD formalism experiment with PULVINI/φ compression."""

    started = time.perf_counter()
    state = golden_phase_state(dimension, phase_seed=phase_seed)
    evolved = state.evolve(golden_ratio_unitary(state.dimension))
    density = evolved.density_matrix()
    numpy = _require_numpy()
    from .pulvini_phi_memory import PulviniPhiMemoryCompressionEngine

    compressor = PulviniPhiMemoryCompressionEngine(fold_depth=fold_depth)
    compression = compressor.compress(density)
    elapsed = time.perf_counter() - started
    return CTDExperimentPacket(
        dimension=state.dimension,
        norm_before=float(numpy.linalg.norm(state.amplitudes)),
        norm_after=float(numpy.linalg.norm(evolved.amplitudes)),
        born_sum=float(numpy.sum(evolved.born_probabilities())),
        density_trace=float(numpy.trace(density).real),
        density_hermiticity_error=float(
            numpy.linalg.norm(density - density.conj().T, ord="fro")
        ),
        compression_ratio=float(compression.working_set_compression_ratio),
        reconstruction_error=float(compression.reconstruction_error),
        reversible_compression=bool(compression.reversible),
        phi=float(PHI),
        elapsed_seconds=float(elapsed),
        claim_review=review_ctd_claims(),
    )


__all__ = [
    "BuresManifold",
    "CTDClaimReview",
    "CTDExperimentPacket",
    "DeutschPulviniBenchmarkReport",
    "DeutschPulviniBenchmarkRow",
    "HilbertState",
    "compute_phi_resonance",
    "dense_state_bytes",
    "golden_phase_state",
    "golden_ratio_unitary",
    "phi_log_bond_dimension",
    "review_ctd_claims",
    "run_deutsch_pulvini_benchmark",
    "run_ctd_formalism_experiment",
    "structured_mps_bytes",
]
