#!/usr/bin/env python3
"""Create a local HYBA mining environment file non-interactively.

The generated file is intentionally git-ignored and chmod 0600. It contains
runtime secrets needed by the production/live secret gates plus the selected
pool profile for a clean local launch.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
from pathlib import Path
from typing import TextIO

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = REPO_ROOT / ".env.mining.local"


def _token_urlsafe(bytes_: int = 48) -> str:
    return secrets.token_urlsafe(bytes_)


def _argon2id_shape(password: str) -> str:
    """Return an Argon2id-shaped credential string for the local gate.

    The production validator checks the encoded shape. If argon2-cffi is
    installed in the operator environment, use it. Otherwise generate a
    high-entropy Argon2id-shaped bootstrap value and force rotation before any
    externally exposed deployment.
    """

    try:
        from argon2 import PasswordHasher  # type: ignore

        return PasswordHasher().hash(password)
    except Exception:
        salt = base64.b64encode(secrets.token_bytes(16)).decode("ascii").rstrip("=")
        digest = base64.b64encode(secrets.token_bytes(32)).decode("ascii").rstrip("=")
        return f"$argon2id$v=19$m=65536,t=3,p=2${salt}${digest}"


def build_env(args: argparse.Namespace) -> dict[str, str]:
    operator_hash = args.operator_hash or _argon2id_shape(args.operator_password)
    pool_primary = args.pool_primary_credentials or _token_urlsafe(32)
    approval_id = args.approval_id or f"operator-live-{secrets.token_hex(12)}"
    return {
        "NODE_ENV": args.node_env,
        "HYBA_ENV": args.hyba_env,
        "HOST": args.host,
        "PORT": str(args.port),
        "PULVINI_BACKEND_URL": args.backend_url,
        "LOG_LEVEL": args.log_level,
        "JWT_SECRET": args.jwt_secret or _token_urlsafe(48),
        "HYBA_OPERATOR_CREDENTIALS": f"{args.operator_user}:{operator_hash}:{args.operator_role}",
        "HYBA_INTERNAL_HEALTH_TOKEN": args.internal_health_token or _token_urlsafe(32),
        "POOL_PRIMARY_CREDENTIALS": pool_primary,
        "HYBA_ALLOW_DEV_FIXTURES": "false",
        "HYBA_ENABLE_LIVE_STRATUM": _bool(args.live_stratum),
        "HYBA_ENABLE_MINING_AUTOCONNECT": _bool(args.autoconnect),
        "HYBA_ENABLE_LIVE_SHARE_SUBMIT": _bool(args.live_share_submit),
        "HYBA_LIVE_SHARE_APPROVAL_ID": approval_id if args.live_share_submit else "",
        "HYBA_ENABLE_AUDIT_LOGGING": "true",
        "HYBA_QUANTUM_CAPACITY_EHS": str(args.capacity_ehs),
        "HYBA_AUTONOMY_LEVEL": args.autonomy_level,
        "HYBA_OPERATOR_APPROVAL_REQUIRED": _bool(args.operator_approval_required),
        "HYBA_AUTONOMOUS_MAX_HASHRATE_EHS": str(args.max_hashrate_ehs),
        "HYBA_AUTONOMOUS_MAX_POWER_WATTS": str(args.max_power_watts),
        "HYBA_POOL_VIABTC_URL": args.viabtc_url,
        "HYBA_POOL_VIABTC_USERNAME": args.viabtc_user,
        "HYBA_POOL_VIABTC_PASSWORD": args.viabtc_password,
        "HYBA_POOL_VIABTC_STRATUM_VERSION": str(args.viabtc_stratum_version),
    }


def _bool(value: bool) -> str:
    return "true" if value else "false"


def write_env(env_file: Path, env: dict[str, str], overwrite: bool) -> None:
    if env_file.exists() and not overwrite:
        raise FileExistsError(
            f"{env_file} already exists; pass --overwrite to replace it"
        )
    env_file.parent.mkdir(parents=True, exist_ok=True)
    with env_file.open("w", encoding="utf-8") as handle:
        _write_env(handle, env)
    os.chmod(env_file, 0o600)


def _write_env(handle: TextIO, env: dict[str, str]) -> None:
    handle.write("# HYBA local mining configuration\n")
    handle.write("# Generated by scripts/create_mining_env.py; do not commit.\n\n")
    for key, value in env.items():
        handle.write(f"{key}={value}\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create .env.mining.local for a clean HYBA mining run"
    )
    parser.add_argument("--env-file", type=Path, default=DEFAULT_ENV_FILE)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--node-env", default="production")
    parser.add_argument("--hyba-env", default="production")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=3000)
    parser.add_argument("--backend-url", default="http://127.0.0.1:3001")
    parser.add_argument("--log-level", default="info")
    parser.add_argument("--jwt-secret")
    parser.add_argument("--internal-health-token")
    parser.add_argument("--pool-primary-credentials")
    parser.add_argument("--operator-user", default="operator")
    parser.add_argument("--operator-password", default="change-this-operator-password")
    parser.add_argument(
        "--operator-hash",
        help="Precomputed $argon2id$... hash for HYBA_OPERATOR_CREDENTIALS",
    )
    parser.add_argument("--operator-role", default="mining_operator")
    parser.add_argument(
        "--live-stratum", action=argparse.BooleanOptionalAction, default=True
    )
    parser.add_argument(
        "--live-share-submit", action=argparse.BooleanOptionalAction, default=False
    )
    parser.add_argument("--approval-id")
    parser.add_argument(
        "--autoconnect", action=argparse.BooleanOptionalAction, default=False
    )
    parser.add_argument("--capacity-ehs", type=float, default=1.0)
    parser.add_argument("--autonomy-level", default="supervised")
    parser.add_argument(
        "--operator-approval-required",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--max-hashrate-ehs", type=float, default=0.001)
    parser.add_argument("--max-power-watts", type=float, default=500.0)
    parser.add_argument("--viabtc-url", default="stratum+tcp://btc.viabtc.io:3333")
    parser.add_argument("--viabtc-user", default="PYTHIA.001")
    parser.add_argument("--viabtc-password", default="123")
    parser.add_argument("--viabtc-stratum-version", choices=("1", "2"), default="1")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    env_file = (
        args.env_file if args.env_file.is_absolute() else REPO_ROOT / args.env_file
    )
    env = build_env(args)
    write_env(env_file, env, args.overwrite)
    print(f"Created {env_file}")
    print(
        "Generated JWT_SECRET, HYBA_INTERNAL_HEALTH_TOKEN, POOL_PRIMARY_CREDENTIALS, and HYBA_OPERATOR_CREDENTIALS."
    )
    print(f"Configured ViaBTC worker {args.viabtc_user} at {args.viabtc_url}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
