"""Organism CNS Router - Unified Sensory, Immune, Cognitive, and Metabolic endpoints."""

from __future__ import annotations

from fastapi import APIRouter, Depends
from .immune_schema import RealityAnchorReport, ImmuneStatus
from .cognitive_schema import Conjecture, MetabolicFlux
from hyba_genesis_api.core.substrate import get_substrate

router = APIRouter(prefix="/organism", tags=["Organism CNS"])


# --- SENSORY LOBE ---
@router.get("/senses/reality", response_model=RealityAnchorReport)
async def get_reality_anchor(substrate=Depends(get_substrate)):
    """Detects if the system is in a simulation via Mass-Gap jitter analysis."""
    return substrate.sensory_protocol.verify_reality()


# --- IMMUNE LOBE ---
@router.get("/immune/status", response_model=ImmuneStatus)
async def get_immune_status(substrate=Depends(get_substrate)):
    """Checks Phi-floor and module inseparability."""
    return substrate.immune_system.get_status()


@router.post("/immune/quarantine/{lane_id}")
async def quarantine_lane(lane_id: int, substrate=Depends(get_substrate)):
    """Manually isolate a lane that fails the inseparability audit."""
    return substrate.immune_system.isolate_lane(lane_id)


# --- COGNITIVE LOBE ---
@router.get("/cognition/conjectures", response_model=list[Conjecture])
async def get_conjectures(substrate=Depends(get_substrate)):
    """Lists current self-optimization hypotheses generated by the Reflexive Controller."""
    return substrate.reflexive_controller.get_active_conjectures()


@router.post("/cognition/evolve/{conjecture_id}")
async def approve_evolution(conjecture_id: str, substrate=Depends(get_substrate)):
    """Operator signature to apply a self-optimization proposal to the live manifold."""
    return substrate.reflexive_controller.apply_conjecture(conjecture_id)


# --- METABOLIC LOBE ---
@router.get("/metabolism/flux", response_model=MetabolicFlux)
async def get_metabolic_flux(substrate=Depends(get_substrate)):
    """Measures the energy-to-intelligence conversion rate."""
    return substrate.metabolism.get_current_flux()
